export const COUNTRY_NAMES: Record<string, string> = {
  AO: "Angola",
  AU: "Australia",
  BF: "Burkina Faso",
  BI: "Burundi",
  BJ: "Benin",
  BR: "Brazil",
  BW: "Botswana",
  CA: "Canada",
  CD: "DR Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CI: "Côte d'Ivoire",
  CM: "Cameroon",
  CN: "China",
  CV: "Cape Verde",
  DE: "Germany",
  DJ: "Djibouti",
  DZ: "Algeria",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ET: "Ethiopia",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GH: "Ghana",
  GM: "Gambia",
  GN: "Guinea",
  GQ: "Equatorial Guinea",
  GW: "Guinea-Bissau",
  IN: "India",
  JP: "Japan",
  KE: "Kenya",
  KM: "Comoros",
  LR: "Liberia",
  LS: "Lesotho",
  LY: "Libya",
  MA: "Morocco",
  MG: "Madagascar",
  ML: "Mali",
  MR: "Mauritania",
  MU: "Mauritius",
  MW: "Malawi",
  MZ: "Mozambique",
  NA: "Namibia",
  NE: "Niger",
  NG: "Nigeria",
  RW: "Rwanda",
  SC: "Seychelles",
  SD: "Sudan",
  SL: "Sierra Leone",
  SN: "Senegal",
  SO: "Somalia",
  SS: "South Sudan",
  ST: "São Tomé and Príncipe",
  SZ: "Eswatini",
  TD: "Chad",
  TG: "Togo",
  TN: "Tunisia",
  TZ: "Tanzania",
  UG: "Uganda",
  US: "United States",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const COUNTRY_IDS: Record<string, string> = {
  angola: "AO",
  australia: "AU",
  "burkina faso": "BF",
  burundi: "BI",
  benin: "BJ",
  brazil: "BR",
  botswana: "BW",
  canada: "CA",
  "dr congo": "CD",
  "democratic republic of congo": "CD",
  "democratic republic of the congo": "CD",
  congo: "CG",
  "republic of the congo": "CG",
  "central african republic": "CF",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  "côte d'ivoire": "CI",
  cameroon: "CM",
  china: "CN",
  "cape verde": "CV",
  germany: "DE",
  djibouti: "DJ",
  algeria: "DZ",
  egypt: "EG",
  "western sahara": "EH",
  eritrea: "ER",
  ethiopia: "ET",
  france: "FR",
  gabon: "GA",
  "united kingdom": "GB",
  uk: "GB",
  ghana: "GH",
  gambia: "GM",
  guinea: "GN",
  "equatorial guinea": "GQ",
  "guinea-bissau": "GW",
  india: "IN",
  japan: "JP",
  kenya: "KE",
  comoros: "KM",
  liberia: "LR",
  lesotho: "LS",
  libya: "LY",
  morocco: "MA",
  madagascar: "MG",
  mali: "ML",
  mauritania: "MR",
  mauritius: "MU",
  malawi: "MW",
  mozambique: "MZ",
  namibia: "NA",
  niger: "NE",
  nigeria: "NG",
  rwanda: "RW",
  seychelles: "SC",
  sudan: "SD",
  "sierra leone": "SL",
  senegal: "SN",
  somalia: "SO",
  "south sudan": "SS",
  "sao tome and principe": "ST",
  "são tomé and príncipe": "ST",
  eswatini: "SZ",
  swaziland: "SZ",
  chad: "TD",
  togo: "TG",
  tunisia: "TN",
  tanzania: "TZ",
  uganda: "UG",
  "united states": "US",
  usa: "US",
  "south africa": "ZA",
  zambia: "ZM",
  zimbabwe: "ZW",
};
